# Site settings
title: LAMFO
header-img: img/home-bg.jpg
email: lamfo/(at)unb/(dot)br
copyright_name: LAMFO - UNB
description: "Laboratório de Aprendizado de Máquina Aplicado a Finanças e Organizações"
url: "http://lamfo.unb.br/"
github_username:  lamfo-unb
facebook_username:  lamfounb
email_username:  lamfo/(at)unb/(dot)br

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-97417743-1

# Build settings
markdown: redcarpet
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
